[phases.setup]
nixPkgs = ["...", "nodejs"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-interaction",
    "npm install"
]

[phases.build]
cmds = [
    "npm run build",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache",
    "php artisan event:cache"
]

[start]
cmd = "bash scripts/railway-start.sh"
